import { Link,NavLink,Outlet,Navigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { api } from './api';
import { useAuth } from './auth';
import type { Cart,Product } from './types';
import { money } from './types';

export function Logo(){return <Link to="/" className="text-2xl font-black tracking-tight"><span className="text-lime-500">sport</span>ivo</Link>}
export function ProductCard({product}:{product:Product}){return <Link to={`/shop/${product.slug}`} className="group block"><div className="overflow-hidden rounded-2xl bg-white"><img src={product.image_url??''} alt={product.name} className="aspect-square w-full object-cover transition duration-500 group-hover:scale-105"/></div><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">{product.brand}</p><div className="mt-1 flex items-start justify-between gap-3"><h3 className="font-bold group-hover:underline">{product.name}</h3><span className="whitespace-nowrap font-bold">{money(product.price_cents)}</span></div></Link>}
export function StoreLayout(){const{user,logout}=useAuth();const{data}=useQuery({queryKey:['cart'],queryFn:()=>api.get<{data:Cart}>('/cart')});return <div className="min-h-screen bg-[#f5f6f2] text-slate-900"><header className="sticky top-0 z-30 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Logo/><nav className="hidden items-center gap-7 text-sm font-semibold md:flex"><NavLink to="/shop">Shop</NavLink><NavLink to="/shop?category=running">Running</NavLink><NavLink to="/shop?category=fitness">Fitness</NavLink><NavLink to="/shop?category=outdoor">Outdoor</NavLink></nav><div className="flex items-center gap-4 text-sm font-semibold">{user?<><Link to="/dashboard" className="hidden sm:block">{user.name}</Link><button onClick={()=>void logout()} className="hidden text-slate-500 sm:block">Log out</button></>:<Link to="/login">Log in</Link>}<Link to="/cart" className="rounded-full bg-slate-950 px-4 py-2 text-white">Bag · {data?.data.count??0}</Link></div></div></header><Outlet/><footer className="mt-20 border-t bg-slate-950 text-slate-300"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-3 lg:px-8"><div><Logo/><p className="mt-4 max-w-xs text-sm leading-6 text-slate-400">Performance equipment for every move, every day and every adventure.</p></div><div><p className="font-bold text-white">Explore</p><div className="mt-4 grid gap-2 text-sm"><Link to="/shop">Shop all</Link><Link to="/cart">Your bag</Link><Link to="/dashboard">Account</Link></div></div><div><p className="font-bold text-white">Built differently.</p><p className="mt-4 text-sm text-slate-400">Symfony 7.4 API + React TypeScript.</p></div></div></footer></div>}
export function GuestLayout(){return <div className="flex min-h-screen flex-col bg-[#f7f8fa]"><header className="border-b bg-white px-6 py-5"><Logo/></header><main className="flex flex-1 items-center justify-center px-5 py-12"><div className="w-full max-w-md rounded-3xl bg-white px-7 py-8 shadow-sm sm:px-10"><Outlet/></div></main><footer className="py-6 text-center text-xs text-slate-400">© 2026 Sportivo · Europe</footer></div>}
export function AdminLayout(){const{user,logout}=useAuth();return <div className="min-h-screen bg-slate-100 lg:grid lg:grid-cols-[260px_1fr]"><aside className="bg-slate-950 p-6 text-white lg:min-h-screen"><div className="text-xl font-black"><span className="text-lime-400">sport</span>ivo <span className="text-xs uppercase tracking-widest text-slate-400">admin</span></div><nav className="mt-10"><NavLink to="/admin/orders" className={({isActive})=>`block rounded-xl px-4 py-3 text-sm font-semibold ${isActive?'bg-lime-400 text-slate-950':'text-slate-300'}`}>Orders</NavLink></nav><div className="mt-10 border-t border-slate-800 pt-6"><p className="font-semibold">{user?.name}</p><p className="text-xs text-slate-400">{user?.email}</p><button onClick={()=>void logout()} className="mt-4 text-sm text-slate-300">Log out</button></div></aside><main className="p-5 md:p-10"><Outlet/></main></div>}
export function Protected({admin=false}:{admin?:boolean}){const{user,ready}=useAuth();if(!ready)return <div className="grid min-h-screen place-items-center font-bold">Loading…</div>;if(!user)return <Navigate to="/login" replace/>;if(admin&&!user.roles.some(role=>['ROLE_ADMIN','ROLE_SUPERADMIN'].includes(role)))return <Navigate to="/" replace/>;return <Outlet/>}
export function ErrorText({message}:{message?:string}){return message?<p className="mt-1 text-xs font-semibold text-red-600">{message}</p>:null}
