import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { api,RequestError } from '../api';
import { useAuth } from '../auth';
import type { Order } from '../types';
import { money } from '../types';

export function DashboardPage(){const{user}=useAuth();const{data,isLoading}=useQuery({queryKey:['my-orders'],queryFn:()=>api.get<{data:Order[]}>('/me/orders')});return <main className="mx-auto max-w-6xl px-5 py-14 lg:px-8"><div className="flex items-end justify-between"><div><p className="eyebrow">Your account</p><h1 className="mt-3 text-4xl font-black">Hello, {user?.name}</h1></div><Link to="/profile" className="rounded-full border bg-white px-5 py-2 text-sm font-bold">Edit profile</Link></div><section className="panel mt-10"><h2 className="text-xl font-black">Your orders</h2>{isLoading?<p className="mt-6 text-slate-500">Loading…</p>:!data?.data.length?<p className="mt-6 text-slate-500">No orders yet. <Link to="/shop" className="font-bold underline">Start shopping</Link></p>:<div className="mt-5 divide-y">{data.data.map(order=><Link to={`/orders/${order.number}`} key={order.id} className="grid gap-2 py-5 sm:grid-cols-4"><strong>{order.number}</strong><span className="capitalize text-slate-500">{order.status.replaceAll('_',' ')}</span><span>{new Date(order.created_at).toLocaleDateString()}</span><strong className="sm:text-right">{money(order.total_cents)}</strong></Link>)}</div>}</section></main>}
export function ProfilePage(){const{user,refreshUser,logout}=useAuth();const[notice,setNotice]=useState('');const profile=useForm<{name:string;email:string}>({defaultValues:{name:user?.name,email:user?.email}});const password=useForm<{current_password:string;password:string}>();const deletion=useForm<{password:string}>();const save=profile.handleSubmit(async data=>{try{await api.patch('/profile',data);await refreshUser();setNotice('Profile saved.');}catch(e){if(e instanceof RequestError)Object.entries(e.payload.errors).forEach(([f,m])=>profile.setError(f as 'name'|'email',{message:m[0]}));}});const change=password.handleSubmit(async data=>{try{await api.put('/profile/password',data);password.reset();setNotice('Password updated.');}catch(e){if(e instanceof RequestError)Object.entries(e.payload.errors).forEach(([f,m])=>password.setError(f as 'password'|'current_password',{message:m[0]}));}});const remove=deletion.handleSubmit(async data=>{await api.delete('/profile',data);await logout();location.href='/';});return <main className="mx-auto max-w-3xl px-5 py-14"><p className="eyebrow">Settings</p><h1 className="mt-3 text-4xl font-black">Profile</h1>{notice&&<p className="mt-5 rounded-xl bg-lime-100 p-4 font-semibold">{notice}</p>}<form onSubmit={save} className="panel mt-8 space-y-4"><h2 className="text-xl font-black">Profile information</h2><input className="field" {...profile.register('name')}/><input className="field" type="email" {...profile.register('email')}/><button className="btn-primary">Save changes</button></form><form onSubmit={change} className="panel mt-5 space-y-4"><h2 className="text-xl font-black">Update password</h2><input className="field" type="password" placeholder="Current password" {...password.register('current_password')}/><input className="field" type="password" placeholder="New password" {...password.register('password')}/><button className="btn-primary">Update password</button></form><form onSubmit={remove} className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-6 space-y-4"><h2 className="text-xl font-black text-red-900">Delete account</h2><p className="text-sm text-red-700">This permanently removes your profile.</p><input className="field" type="password" placeholder="Confirm with password" {...deletion.register('password')}/><button className="rounded-full bg-red-700 px-6 py-3 font-bold text-white">Delete account</button></form></main>}
