import { Link,useParams,useSearchParams } from 'react-router-dom';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { api } from '../api';
import type { Order } from '../types';
import { money } from '../types';

const labels:Record<string,string>={pending_payment:'Pending payment',paid:'Paid',processing:'Processing',shipped:'Shipped',delivered:'Delivered',cancelled:'Cancelled',refunded:'Refunded'};
export function AdminOrdersPage(){const[params,setParams]=useSearchParams();const query=params.toString();const{data,isLoading}=useQuery({queryKey:['admin-orders',query],queryFn:()=>api.get<{data:Order[];meta:{total:number};statuses:string[]}>(`/admin/orders?${query}`)});const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setParams(new URLSearchParams(new FormData(e.currentTarget) as never));};return <div><p className="eyebrow">Operations</p><h1 className="mt-3 text-4xl font-black">Orders</h1><form onSubmit={submit} className="mt-8 flex flex-wrap gap-3"><input name="q" defaultValue={params.get('q')??''} placeholder="Order or email…" className="field max-w-xs"/><select name="status" defaultValue={params.get('status')??''} className="field max-w-xs"><option value="">All statuses</option>{data?.statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select><button className="btn-primary">Filter</button></form><div className="mt-7 overflow-hidden rounded-2xl bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Order</th><th className="p-4">Customer</th><th className="p-4">Status</th><th className="p-4">Total</th></tr></thead><tbody>{isLoading?<tr><td className="p-5" colSpan={4}>Loading…</td></tr>:data?.data.map(order=><tr key={order.id} className="border-t"><td className="p-4"><Link to={`/admin/orders/${order.id}`} className="font-bold underline">{order.number}</Link></td><td className="p-4">{order.email}</td><td className="p-4 capitalize">{labels[order.status]}</td><td className="p-4 font-bold">{money(order.total_cents)}</td></tr>)}</tbody></table></div></div>}
export function AdminOrderPage(){const{id}=useParams();const client=useQueryClient();const{data,isLoading}=useQuery({queryKey:['admin-order',id],queryFn:()=>api.get<{data:{order:Order;next_statuses:string[]}}>(`/admin/orders/${id}`)});const mutation=useMutation({mutationFn:(status:string)=>api.patch(`/admin/orders/${id}/status`,{status}),onSuccess:()=>client.invalidateQueries({queryKey:['admin-order',id]})});if(isLoading||!data)return <p>Loading…</p>;const{order,next_statuses}=data.data;return <div><Link to="/admin/orders" className="text-sm font-semibold">← Orders</Link><div className="mt-4 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Order detail</p><h1 className="mt-3 text-4xl font-black">{order.number}</h1><p className="mt-2 text-slate-500">{new Date(order.created_at).toLocaleString()}</p></div>{next_statuses.length>0&&<select defaultValue="" onChange={e=>e.target.value&&mutation.mutate(e.target.value)} className="field max-w-xs"><option value="" disabled>Change status…</option>{next_statuses.map(s=><option value={s} key={s}>{labels[s]}</option>)}</select>}</div><div className="mt-8 grid gap-5 lg:grid-cols-[1fr_320px]"><section className="panel"><h2 className="text-xl font-black">Items</h2>{order.items?.map(i=><div key={i.id} className="flex justify-between border-b py-4"><span>{i.name} · {i.variant_name} × {i.quantity}</span><strong>{money(i.line_total_cents)}</strong></div>)}</section><aside className="space-y-5"><div className="panel"><p className="text-xs uppercase text-slate-500">Status</p><p className="mt-2 text-xl font-black capitalize">{labels[order.status]}</p><p className="mt-5 text-3xl font-black">{money(order.total_cents)}</p></div><div className="panel"><h2 className="font-black">Customer</h2><p className="mt-3">{order.email}</p><p className="text-slate-500">{order.phone}</p></div></aside></div></div>}
