import { useEffect,useState } from 'react';
import { Link,useNavigate,useSearchParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { api,RequestError } from '../api';
import { useAuth } from '../auth';
import { ErrorText } from '../components';

export function LoginPage(){const{login,user}=useAuth();const navigate=useNavigate();const{register,handleSubmit,setError,formState:{errors,isSubmitting}}=useForm<{email:string;password:string}>();useEffect(()=>{if(user)navigate('/dashboard',{replace:true})},[user]);const submit=handleSubmit(async data=>{try{await login(data.email,data.password);navigate('/dashboard');}catch(error){if(error instanceof RequestError)setError('email',{message:error.payload.errors.email?.[0]??error.message});}});return <><AuthTitle title="Welcome back" copy="Sign in to see your orders and keep moving."/><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-bold">Email<input className="field mt-2" type="email" {...register('email',{required:'Email is required'})}/><ErrorText message={errors.email?.message}/></label><label className="block text-sm font-bold">Password<input className="field mt-2" type="password" {...register('password',{required:'Password is required'})}/><ErrorText message={errors.password?.message}/></label><div className="flex justify-end"><Link to="/forgot-password" className="text-sm font-semibold underline">Forgot password?</Link></div><button disabled={isSubmitting} className="btn-primary w-full">Log in</button></form><p className="mt-6 text-center text-sm text-slate-500">New here? <Link to="/register" className="font-bold text-slate-950">Create account</Link></p></>}
export function RegisterPage(){const{register:signUp}=useAuth();const navigate=useNavigate();const{register,handleSubmit,setError,formState:{errors,isSubmitting}}=useForm<{name:string;email:string;password:string;accepted_terms:boolean}>();const submit=handleSubmit(async data=>{try{await signUp(data);navigate('/dashboard');}catch(error){if(error instanceof RequestError)Object.entries(error.payload.errors).forEach(([field,messages])=>setError(field as keyof typeof data,{message:messages[0]}));}});return <><AuthTitle title="Join daoSport" copy="Create an account for faster checkout and order history."/><form onSubmit={submit} className="mt-7 space-y-4"><AuthField label="Name" error={errors.name?.message} input={<input className="field mt-2" {...register('name',{required:'Name is required'})}/>}/><AuthField label="Email" error={errors.email?.message} input={<input type="email" className="field mt-2" {...register('email',{required:'Email is required'})}/>}/><AuthField label="Password" error={errors.password?.message} input={<input type="password" className="field mt-2" {...register('password',{required:'Password is required',minLength:{value:8,message:'Use at least 8 characters'}})}/>}/><label className="flex gap-3 text-sm text-slate-600"><input type="checkbox" {...register('accepted_terms',{required:'Accept the terms'})}/> I accept the terms and privacy policy.</label><ErrorText message={errors.accepted_terms?.message}/><button disabled={isSubmitting} className="btn-primary w-full">Create account</button></form><p className="mt-6 text-center text-sm">Already registered? <Link to="/login" className="font-bold">Log in</Link></p></>}
export function ForgotPage(){const[sent,setSent]=useState(false);const{register,handleSubmit,formState:{isSubmitting}}=useForm<{email:string}>();const submit=handleSubmit(async data=>{await api.post('/auth/forgot-password',data);setSent(true)});return <><AuthTitle title="Reset password" copy="We will send a secure reset link to your inbox."/>{sent?<Notice>Check your inbox. In development, open Mailpit on port 8026.</Notice>:<form onSubmit={submit} className="mt-7 space-y-4"><input type="email" placeholder="Email address" className="field" {...register('email',{required:true})}/><button disabled={isSubmitting} className="btn-primary w-full">Email reset link</button></form>}</>}
export function ResetPage(){const[params]=useSearchParams();const navigate=useNavigate();const{register,handleSubmit,setError,formState:{errors,isSubmitting}}=useForm<{password:string}>();const submit=handleSubmit(async data=>{try{await api.post('/auth/reset-password',{token:params.get('token'),password:data.password});navigate('/login');}catch(error){if(error instanceof RequestError)setError('password',{message:error.message});}});return <><AuthTitle title="Choose a new password" copy="Use at least eight characters."/><form onSubmit={submit} className="mt-7 space-y-4"><input type="password" className="field" {...register('password',{required:true,minLength:8})}/><ErrorText message={errors.password?.message}/><button disabled={isSubmitting} className="btn-primary w-full">Update password</button></form></>}
export function VerifyPage(){const[params]=useSearchParams();const[message,setMessage]=useState('Verifying your email…');useEffect(()=>{api.post('/auth/verify-email',{token:params.get('token')}).then(()=>setMessage('Email verified. You can continue shopping.')).catch(()=>setMessage('This verification link is invalid or expired.'));},[]);return <><AuthTitle title="Email verification" copy={message}/><Link to="/" className="btn-primary mt-7 w-full">Back to store</Link></>}
function AuthTitle({title,copy}:{title:string;copy:string}){return <div><p className="eyebrow">Your account</p><h1 className="mt-3 text-3xl font-black">{title}</h1><p className="mt-3 text-sm leading-6 text-slate-500">{copy}</p></div>};function AuthField({label,input,error}:{label:string;input:React.ReactNode;error?:string}){return <label className="block text-sm font-bold">{label}{input}<ErrorText message={error}/></label>};function Notice({children}:{children:React.ReactNode}){return <div className="mt-7 rounded-xl bg-blue-100 p-4 text-sm font-semibold text-blue-900">{children}</div>}
