<?php

namespace App\Tests\Functional;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

final class ApiTest extends WebTestCase
{
    public function testHealthAndCatalogUseTheJsonEnvelope():void{$client=static::createClient();$client->request('GET','/api/health');self::assertResponseIsSuccessful();self::assertSame('ok',$this->payload($client)['data']['status']);$client->request('GET','/api/products');self::assertResponseIsSuccessful();$payload=$this->payload($client);self::assertArrayHasKey('data',$payload);self::assertArrayHasKey('meta',$payload);self::assertNotEmpty($payload['data']);}
    public function testUserCanLoginAndReadProfile():void{$client=static::createClient();$client->jsonRequest('POST','/api/auth/login',['email'=>'test@example.com','password'=>'password']);self::assertResponseIsSuccessful();$token=$this->payload($client)['data']['access_token'];$client->request('GET','/api/profile',server:['HTTP_AUTHORIZATION'=>'Bearer '.$token]);self::assertResponseIsSuccessful();self::assertSame('test@example.com',$this->payload($client)['data']['email']);}
    public function testRegularUserCannotOpenAdminOrders():void{$client=static::createClient();$client->jsonRequest('POST','/api/auth/login',['email'=>'test@example.com','password'=>'password']);self::assertResponseIsSuccessful();$token=$this->payload($client)['data']['access_token'];$client->setServerParameter('HTTP_AUTHORIZATION','Bearer '.$token);$client->request('GET','/api/admin/orders');self::assertResponseStatusCodeSame(403);}
    public function testValidationErrorsHaveStableShape():void{$client=static::createClient();$client->jsonRequest('POST','/api/auth/register',['email'=>'bad']);self::assertResponseStatusCodeSame(422);$payload=$this->payload($client);self::assertArrayHasKey('message',$payload);self::assertArrayHasKey('errors',$payload);}
    public function testGuestCanCheckoutAndReadTheLastOrder():void{$client=static::createClient();$client->request('GET','/api/products/cloudswift-4');$variantId=$this->payload($client)['data']['product']['variants'][0]['id'];$client->request('GET','/api/cart');$client->jsonRequest('POST','/api/cart/items',['variant_id'=>$variantId,'quantity'=>2]);self::assertResponseStatusCodeSame(201);$client->jsonRequest('POST','/api/orders',['email'=>'guest@example.com','phone'=>'123456789','first_name'=>'Guest','last_name'=>'Buyer','line1'=>'Street 1','city'=>'Warsaw','postal_code'=>'00-001','country'=>'PL','delivery_method'=>'standard']);self::assertResponseStatusCodeSame(201);$order=$this->payload($client)['data'];self::assertSame(33800,$order['total_cents']);$client->request('GET','/api/orders/'.$order['number']);self::assertResponseIsSuccessful();self::assertSame($order['number'],$this->payload($client)['data']['number']);}
    public function testRefreshCookieIsRotated():void{$client=static::createClient();$client->jsonRequest('POST','/api/auth/login',['email'=>'test@example.com','password'=>'password']);self::assertResponseIsSuccessful();$firstCookies=$client->getCookieJar()->all();self::assertNotEmpty($firstCookies);$first=$firstCookies[0]->getValue();$client->jsonRequest('POST','/api/auth/refresh');self::assertResponseIsSuccessful();$secondCookies=$client->getCookieJar()->all();self::assertNotEmpty($secondCookies);self::assertNotSame($first,$secondCookies[0]->getValue());}
    private function payload($client):array{return json_decode((string)$client->getResponse()->getContent(),true,512,JSON_THROW_ON_ERROR);}
}
