import { Link } from '@inertiajs/react';
import StoreLayout from '@/Layouts/StoreLayout';
import ProductCard from '@/Components/ProductCard';
import { useI18n } from '@/lib/i18n';

export default function Catalog({ products, categories, filters }) {
    const t = useI18n();
    return <StoreLayout title={t('catalog_title')}><main className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.25em] text-blue-600">{t('catalog_eyebrow')}</p><h1 className="mt-3 text-4xl font-black tracking-tight">{t('catalog_title')}</h1><p className="mt-2 text-sm text-slate-500">{t('catalog_count', { count: products.total })}</p></div><form className="flex gap-2"><input name="q" defaultValue={filters.q} placeholder={t('catalog_search')} className="rounded-full border-slate-200 bg-white px-5 py-2 text-sm" /><select name="sort" defaultValue={filters.sort} className="rounded-full border-slate-200 bg-white px-4 py-2 text-sm"><option value="">{t('catalog_latest')}</option><option value="price_asc">{t('catalog_price_asc')}</option><option value="price_desc">{t('catalog_price_desc')}</option></select><button className="rounded-full bg-slate-950 px-5 py-2 text-sm font-bold text-white">{t('catalog_go')}</button></form></div><div className="mt-10 flex gap-2 overflow-x-auto pb-2"><Link href={route('store.catalog')} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${!filters.category ? 'bg-slate-950 text-white' : 'bg-white'}`}>{t('catalog_all')}</Link>{categories.map(c => <Link key={c.id} href={route('store.catalog', { category: c.slug })} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${filters.category === c.slug ? 'bg-slate-950 text-white' : 'bg-white'}`}>{c.localized_name ?? c.name}</Link>)}</div><div className="mt-8 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3 lg:grid-cols-4 lg:gap-x-6">{products.data.map(p => <ProductCard key={p.id} product={p} />)}</div>{products.links.length > 3 && <div className="mt-12 flex justify-center gap-2">{products.links.map((l, i) => <Link key={i} href={l.url || '#'} className={`rounded-full px-4 py-2 text-sm ${l.active ? 'bg-slate-950 text-white' : 'bg-white'} ${!l.url ? 'pointer-events-none opacity-30' : ''}`} dangerouslySetInnerHTML={{ __html: l.label }} />)}</div>}</main></StoreLayout>;
}
