import { Head, Link, usePage } from '@inertiajs/react';
import { useState } from 'react';

export default function StoreLayout({ children, title = 'Sportivo' }) {
    const { auth, flash } = usePage().props;
    const [open, setOpen] = useState(false);
    return <div className="min-h-screen bg-[#f7f8fa] text-slate-900"><Head title={title} />
        <div className="bg-slate-950 px-4 py-2 text-center text-xs font-medium tracking-wide text-white">Free shipping on orders over €50 · Easy 30-day returns</div>
        <header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-5 px-5 py-4 lg:px-8">
            <button onClick={() => setOpen(!open)} className="rounded-lg p-2 lg:hidden" aria-label="Open menu">☰</button><Link href={route('store.home')} className="text-2xl font-black tracking-tight"><span className="text-lime-500">sport</span>ivo</Link>
            <nav className={`${open ? 'absolute left-0 right-0 top-full flex' : 'hidden'} flex-col gap-4 border-b bg-white p-5 text-sm font-semibold lg:static lg:flex lg:flex-row lg:border-0 lg:bg-transparent lg:p-0`}><Link href={route('store.catalog')}>Shop all</Link><Link href={route('store.catalog', { category: 'running' })}>Running</Link><Link href={route('store.catalog', { category: 'fitness' })}>Fitness</Link><Link href={route('store.catalog', { category: 'tennis' })}>Racket sports</Link><Link href={route('store.catalog', { category: 'outdoor' })}>Outdoor</Link></nav>
            <form action={route('store.catalog')} className="ml-auto hidden max-w-xs flex-1 md:flex"><input name="q" placeholder="Search products, brands..." className="w-full rounded-full border-slate-200 bg-slate-50 px-5 py-2.5 text-sm focus:border-lime-500 focus:ring-lime-500" /></form>
            <div className="flex items-center gap-2 text-sm"><Link href={auth.user ? route('dashboard') : route('login')} className="hidden rounded-full p-2 hover:bg-slate-100 sm:block">♙ <span className="hidden xl:inline">Account</span></Link><Link href={route('store.cart')} className="rounded-full bg-slate-950 px-4 py-2.5 font-semibold text-white">Bag <span className="text-lime-300">↗</span></Link></div>
        </div></header>
        {flash?.success && <div className="mx-auto mt-4 max-w-7xl rounded-xl bg-lime-100 px-5 py-3 text-sm font-medium text-lime-900">{flash.success}</div>}{flash?.error && <div className="mx-auto mt-4 max-w-7xl rounded-xl bg-red-100 px-5 py-3 text-sm text-red-900">{flash.error}</div>}
        {children}<footer className="mt-20 bg-slate-950 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-14 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><div><div className="text-2xl font-black"><span className="text-lime-400">sport</span>ivo</div><p className="mt-4 max-w-xs text-sm leading-6 text-slate-400">Equipment for every way you move. Curated gear, honest advice and fast delivery.</p></div><div><h3 className="font-bold">Shop</h3><div className="mt-4 space-y-3 text-sm text-slate-400"><Link href={route('store.catalog')} className="block">All products</Link><Link href={route('store.catalog', { category: 'running' })} className="block">Running</Link><Link href={route('store.catalog', { category: 'fitness' })} className="block">Fitness</Link></div></div><div><h3 className="font-bold">Help</h3><div className="mt-4 space-y-3 text-sm text-slate-400"><p>Delivery & returns</p><p>Contact us</p><p>Size guide</p></div></div><div><h3 className="font-bold">Stay in the loop</h3><p className="mt-4 text-sm text-slate-400">New drops and training tips, once a week.</p><div className="mt-4 flex"><input className="w-full rounded-l-lg border-0 bg-slate-800 text-sm" placeholder="Email address" /><button className="rounded-r-lg bg-lime-400 px-4 font-bold text-slate-950">→</button></div></div></div><div className="border-t border-slate-800 py-5 text-center text-xs text-slate-500">© 2026 Sportivo · EUR · Europe</div></footer></div>;
}
